### ISSUE TITLE
Mention "make install" in ReadMe

### ISSUE THREAD

**Issue by softpunch** [evanpurkhiser/keyfinder-cli#10]
I'm sure this is obvious for many devs, but it took me a minute to remember.
(And there was a time when I would never have figured it out...)

It would be helpful if you added "make install" to the readme.
As in, update it to say:

> As long as these two dependencies are installed then you should be able to simply type:
> 
> $ make
> **$ make install**

Thanks!

**Comment by evanpurkhiser** [comment]
Sure sounds good!
