### ISSUE TITLE
keyfinder.h, constants.h?

### ISSUE THREAD

**Issue by samyhajal** [evanpurkhiser/keyfinder-cli#4]
Where can I find the files keyfinder.h and constants.h included in keyfinder.cpp?
Thanks

**Comment by evanpurkhiser** [comment]
Install [ibsh/libKeyFinder](https://github.com/ibsh/libKeyFinder).

What operating system are you on?

**Comment by samyhajal** [comment]
osx yosemite

**Comment by samyhajal** [comment]
@EvanPurkhiser I cloned ibsh/libKeyFinder into a local directory. What do you mean by install?

**Comment by evanpurkhiser** [comment]
I haven't tried compiling this on OSX, let me grab my laptop and give compiling this a try. It can help with #3 as well.

**Comment by evanpurkhiser** [comment]
Going to go ahead and merge this thread with #3. I'll post an update there.
