### ISSUE TITLE
Cannot find keyfinder library on OSX using make

### ISSUE THREAD

**Issue by andersfischernielsen** [evanpurkhiser/keyfinder-cli#7]
I get a `ld: library not found for -lkeyfinder` when trying to `make`. 

I'm running El Capitan, have run `qmake`, `make` and `make install` in libKeyFinder, even with the fixes mentioned in the other commit. 

I have a DJ gig tomorrow, but I can't seem to build `keyfinder-cli`.

**Comment by evanpurkhiser** [comment]
Have you seen this https://github.com/ibsh/libKeyFinder/pull/9?

**Comment by andersfischernielsen** [comment]
I just pulled your fork, did everything again. 
I still get 
`ld: library not found for -lkeyfinder`
`clang: error: linker command failed with exit code 1 (use -v to see invocation)`
`make: *** [keyfinder-cli] Error 1`
when trying to make keyfinder-cli. 

Thanks for making this, btw! I hope I can use it soon. :smile:

**Comment by evanpurkhiser** [comment]
And you built from my forked branch `fixup/install-target` right?

Can you verify that after doing `make install` for libKeyFinder is installing the shared object into `/usr/local/lib/libkeyfinder.*`

**Comment by andersfischernielsen** [comment]
Yeah, I built from that branch. :) 

And no, there's no `libkeyfinder.*` lib in `/usr/local/lib/`, unfortunately.

**Comment by evanpurkhiser** [comment]
I discovered an issue with my changes to the Project file in that pull request causing the headers and library files to install into the incorrect place on OSX. See: https://github.com/ibsh/libKeyFinder/pull/9#issuecomment-193675543

Go ahead and rebuild libkeyfinder and see if that solves the issue!

For posterity the build steps I took

``` bash
brew install fftw qt5 ffmpeg
git clone git@github.com:ibsh/libKeyFinder
cd libKeyFinder
git fetch origin pull/9/head:target-fix
git checkout target-fix
/usr/local/opt/qt5/bin/qmake
make
make install

git clone git@github.com:EvanPurkhiser/keyfinder-cli
cd keyfinder-cli
make
```

**Comment by andersfischernielsen** [comment]
Awesome! It works now. :) Thanks.
